### ISSUE TITLE
yarnhook: command not found error

### ISSUE THREAD

**Issue by aki77** [frontsideair/yarnhook#46]
I get an `yarnhook: command not found` error when I try to `git checkout` on v0.4.4.
The following item seem to be missing from package.json in v0.4.4.

https://github.com/frontsideair/yarnhook/blob/v0.4.3/package.json#L4

**Comment by frontsideair** [comment]
Yup, just noticed it and a fix is coming right now. Sorry for inconvenience!

**Comment by frontsideair** [comment]
A [new version](https://github.com/frontsideair/yarnhook/releases/tag/v0.4.5) is published and the issue is closed, but feel free to reopen if it isn't fixed yet.

The problem was caused when I was moving towards a monorepo setup and and accidentally forgot to add the `bin` field in `package.json`. 😞

**Comment by aki77** [comment]
Thanks!
